#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing...'

# Check ESLint Standards
yarn type-check ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn type-check, add changes and try commit again.';
    false;
)

yarn format ||
(
    echo 'oops, cannot format your code. Check your script prop in package.json file and try again.';
    false;
)

echo '🎉 No error found and succesfully format your code!: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged